version: "3.9"

services:
  postgres:
    image: docker.io/postgres:17-bullseye
    container_name: rust_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: oauthserver
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
    driver: local